dotNET/MVC/CSGO/Controllers/PlayersController.cs
using CSGO.Data;
using CSGO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace CSGO.Controllers
{
    public class PlayersController : Controller
    {

        private readonly IPlayerRepository _playerRepository;
        private readonly ITeamRepository _teamRepository;

        public PlayersController(IPlayerRepository playerRepository, ITeamRepository teamRepository)
        {
            _playerRepository = playerRepository;
            _teamRepository = teamRepository;
        }

        [Authorize(Roles = "User, Administrator")]
        public async Task<IActionResult> Index(string nickname)
        {
            if (!String.IsNullOrEmpty(nickname))
                return View(await _playerRepository.GetPlayers(nickname));
            else
                return View(await _playerRepository.GetPlayers());
        }

        // GET: Players/Details/5
        [Authorize(Roles = "User, Administrator")]
        public async Task<IActionResult> Details(int id)
        {
            var player = await _playerRepository.GetPlayer(id);
            if (player == null)
            {
                return View("NotFound");
            }
            return View(player);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            ViewData["TeamId"] = new SelectList(await _teamRepository.GetTeams(), "TeamId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("PlayerId,Name,Surname,Nickname,Salary,DateOfBirth,TeamId")] Player player)
        {
            if (ModelState.IsValid)
            {
                _playerRepository.AddPlayer(player);
                await _playerRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(await _teamRepository.GetTeams(), "TeamId", "Name", player.TeamId);
            return View(player);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id)
        {
            var player = await _playerRepository.GetPlayer(id);
            if (player == null)
            {
                return View("NotFound");
            }
            ViewData["TeamId"] = new SelectList(await _teamRepository.GetTeams(), "TeamId", "Name", player.TeamId);
            return View(player);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerId,Name,Surname,Nickname,Salary,DateOfBirth,TeamId")] Player player)
        {
            if (id != player.PlayerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _playerRepository.UpdatePlayer(player);
                    await _playerRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.PlayerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(await _teamRepository.GetTeams(), "TeamId", "Name", player.TeamId);
            return View(player);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            var player = await _playerRepository.GetPlayer(id);
            if (player == null)
            {
                return View("NotFound");
            }
            return View(player);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _playerRepository.GetPlayer(id);
            _playerRepository.DeletePlayer(id);
            await _playerRepository.Save();
            return RedirectToAction(nameof(Index));
        }

        public bool PlayerExists(int id)
        {
            return _playerRepository.PlayerExists(id);
        }

        public bool PlayerExists(Player p)
        {
            return _playerRepository.PlayerExists(p);
        }
    }
}

dotNET/MVC/CSGO/Controllers/TeamsController.cs
using CSGO.Data;
using CSGO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace CSGO.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ITeamRepository _teamRepository;

        public TeamsController(ITeamRepository teamRepository)
        {
            _teamRepository = teamRepository;
        }

        [Authorize(Roles = "User, Administrator")]
        public async Task<IActionResult> Index(string teamName)
        {
            if (!String.IsNullOrEmpty(teamName))
                return View(await _teamRepository.GetTeams(teamName));
            else
                return View(await _teamRepository.GetTeams());
        }

        [Authorize(Roles = "User, Administrator")]
        public async Task<IActionResult> Details(int id)
        {
            var team = await _teamRepository.GetTeam(id);
            if (team == null)
            {
                return View("NotFound");
            }
            return View(team);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("TeamId,Name,DateOfFounding")] Team team)
        {
            if (ModelState.IsValid)
            {
                _teamRepository.AddTeam(team);
                await _teamRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id)
        {
            var team = await _teamRepository.GetTeam(id);
            if (team == null)
            {
                return View("NotFound");
            }
            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,Name,DateOfFounding")] Team team)
        {
            if (id != team.TeamId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _teamRepository.UpdateTeam(team);
                    await _teamRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            var team = await _teamRepository.GetTeam(id);
            if (team == null)
            {
                return View("NotFound");
            }
            return View(team);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _teamRepository.GetTeam(id);
            _teamRepository.DeleteTeam(id);
            await _teamRepository.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _teamRepository.TeamExists(id);
        }
    }
}

dotNET/MVC/CSGO/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "404 - Not found";
}
<header>
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-danger">404 - Resource not found.</p>
</header>

dotNET/MVC/CSGO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSGO</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @{Html.RenderPartial("_Navbar.cshtml");}
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; CSGO CRUD by <a href="https://www.github.com/jbienias/dotNET"><b name="git">Jan Bienias</b></a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

dotNET/MVC/CSGO/Views/Shared/_LayoutDark.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSGO</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="background: #000; color:lightgray">
    @{Html.RenderPartial("_Navbar.cshtml");}
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; CSGO CRUD by <a href="https://www.github.com/jbienias/dotNET">Jan Bienias</a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

dotNET/MVC/CSGO/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><strong>CSGO</strong></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (User.IsInRole("Administrator") || User.IsInRole("User"))
                {
                    <li><a asp-area="" asp-controller="Players" asp-action="Index" id="players">Players</a></li>
                    <li><a asp-area="" asp-controller="Teams" asp-action="Index" id="teams">Teams</a></li>
                }
                <li><a asp-area="" asp-controller="Home" asp-action="About" id="about">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact" id="contact">Contact</a></li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>